### ISSUE TITLE
OSGi Bundle

### ISSUE THREAD

**Issue by penhorwood** [bcgit/bc-lts-java#1]
I am using Bouncy Castle in my project and would like to use the LTS 2.73.3.  The server software I am using is Lucee which is based on OSGi bundles.  Since it appears that with just a few entries in the Manaifest.MF file a OSGi bundle would be created I was wondering if there was any plans to create OSGi bundles for 2.73.3.

**Comment by dghgit** [comment]
Yes, I think we can do this. Would you be able to suggest what's required? It would be good to get a minimal configuration added if possible. Thanks.

**Comment by penhorwood** [comment]
I found these sites on what is needed in a bundle.

- https://spring.io/blog/2008/02/18/creating-osgi-bundles
- https://www.ibm.com/docs/en/wasdtfe?topic=overview-osgi-bundles

It appears that this tool was created to turn jar files into bundles.  I haven't used it yet.
https://bnd.bndtools.org/

**Comment by penhorwood** [comment]
https://bnd.bndtools.org/chapters/390-wrapping.html

![image](https://github.com/bcgit/bc-lts-java/assets/1919238/52586c3e-40e9-4960-837d-38b38129842f)

**Comment by penhorwood** [comment]
https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-multireleasejar

**This section:**

3.2.8 Multi-release JAR
A bundle JAR file can be a multi-release JAR. See [[28] Multi-release JAR File](https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-ref.multireleasejar). When a bundle is a multi-release JAR, that is, the manifest contains

Multi-Release: true
then the Framework must look for a supplemental manifest file, OSGI-INF/MANIFEST.MF, in the versioned directories. For example:

META-INF/versions/9/OSGI-INF/MANIFEST.MF
The Framework must first look in the versioned directory for the major version of the current Java platform and then prior versioned directories in descending order. The first supplemental manifest file found must be used and the Framework must replace the values of the following manifest headers in the manifest with the values of these headers, if present, in the supplemental manifest file.

Import-Package

Require-Capability

Any other headers in the supplemental manifest file must be ignored.

**Comment by penhorwood** [comment]
https://blog.osgi.org/2018/02/osgi-r7-highlights-java-9-support.html

**Comment by dghgit** [comment]
Thanks for the links. Not having much luck with this so far though. Using BND 7.0.0 we have been able to produce an OSGI manifest but no matter what is tried it appears the tool removes what is in the versions hierarchy in META-INF so while the jar comes out with "Multi-Release: true" in it, it has not got any multi-release files in it. Does anyone have any suggestions? It seems like we're missing something obvious, but I've no idea what.

**Comment by penhorwood** [comment]
While I did play with BND a bit too and some other OSGi tools I never figured them out.  I do know that the standard Java BC version does have OSGi manifest but they seem to have issues after version 1.69.

**Comment by penhorwood** [comment]
What toolset are you using to build the jar files?  I see a number of tools for building the OSGi bundle Manifest files but most of them are build tool specific.

**Comment by dghgit** [comment]
We're using gradle - we're probably not doing the best job with multi-release in that either as when we started multi-release was basically not supported. Are you suggesting the best approach would be to try and use the gradle plugin? Previously we've been using the bnd tool directly.

**Comment by penhorwood** [comment]
I am not sure what the best approach would be but I will research using the gradle plugin.  It would be nice if this could be just another step in your build process.

**Comment by dghgit** [comment]
I think I've managed to get the gradle plugin to work properly. Try the jars in:

 https://downloads.bouncycastle.org/betas/bc-lts-2.73.4-SNAPSHOT.zip

And let me know how it goes. If this works we should be able to generate a release soon.

**Comment by penhorwood** [comment]
The manifest is missing **Export-Package:** info

https://academy.jahia.com/documentation/jahia/jahia-8/developer/module-development/using-libraries-in-an-osgi-module/package-dependencies-and-exports

**Comment by dghgit** [comment]
Okay, seems my breathing a sigh of relief when the OSGI-INF files showed up was misplaced.

Try https://downloads.bouncycastle.org/betas/bc-lts-2.73.4-SNAPSHOT.zip now

sha256sum
808487b1647e237d1d2d8a7eb745866d5477957b3c10fd2868790ea834b69487  bc-lts-2.73.4-SNAPSHOT.zip

**Comment by penhorwood** [comment]
Thanks for working on this it will really help me out.

**Comment by dghgit** [comment]
It doesn't seem to be able to deal with the SNAPSHOT very well. I've generated in a set of jars as just 2.73.4. I've put them in the -SNAPSHOT.zip file again though. Try those and let me know how it goes. I think the version info is correct now on import - you'll only see version info in the non provider jars like bcutil and bcpkix. In theory this should be the end of it.

sha256sum bc-lts-2.73.4-SNAPSHOT.zip 
43c15b5ce611a368097147ad3185ecf2e1c5020a2d44fd81404e2282610f5d33  bc-lts-2.73.4-SNAPSHOT.zip

**Comment by penhorwood** [comment]
It works!

**Comment by penhorwood** [comment]
I upgraded to the latest version of the server software and things stopped working.  The issue is Bouncy Castle version 1.38 is used by the server itself.  The server already has 3 bouncy castle jars installed which are exporting 1.38 versions of Bouncy Castle.  I think this is where the uses: clauses comes into play.

https://spring.io/blog/2008/10/20/understanding-the-osgi-uses-directive

I find their explanation complicated but I do see issues with some of the imports in the 2.73.x Manifest where there is no version information.  I removed the 3 jar files that are exporting version 1.38 and the code starting working again.  So it is most likely this a the wrong versions of Bouncy Castle are being wired up wrong.

**Comment by dghgit** [comment]
1.38 is kind of old... they should think about updating... Can you tell which imports seem to be missing version information? As far as I can tell here, they all should have version information. 

One thing, I am assuming bccore has not been included and bcprov is being used.

**Comment by penhorwood** [comment]
I have limited visibility into the wiring issue but the class I can't find is  org.bouncycastle.openssl.PEMParser
Since your classes aren't signed I should be able to hacking in some version info to see if it works.  I am busy reading about Import-Package: and Export-Package:

Here is the Import-Package line think should have version info:
**org.bouncycastle.openssl;resolution:=optional**

It will most likely be tomorrow before I know any more about this. - I live in Central Time USA

**Comment by penhorwood** [comment]
I am taking up the 1.38 issue with the server people.

**Comment by dghgit** [comment]
PEMParser is in the bcpkix jar. Hmm... it looks like there's an import statement for it in the bcpkix MANIFEST as well as an export for it though.

**Comment by penhorwood** [comment]
File:   **bcpkix-lts8on-2.73.4.jar**  -  \META-INF\MANIFEST.MF
Changing Import-Package line:
FROM
**org.bouncycastle.openssl;resolution:=optional**
To
**org.bouncycastle.openssl;resolution:=optional;version="[2.73,3)"**

Seems to have fixed my issue with the server.

**Comment by dghgit** [comment]
Okay, interesting. Is seems I can do this.

I've uploaded a new https://downloads.bouncycastle.org/betas/bc-lts-2.73.4-SNAPSHOT.zip

sha256sum bc-lts-2.73.4-SNAPSHOT.zip 
b2d129ec824256cdd127099545e230a4da52283bcd9d49dca8ea33cc5a4a18ba  bc-lts-2.73.4-SNAPSHOT.zip

Let me know how it goes. Thanks.

**Comment by penhorwood** [comment]
I spent a bit of last night thinking about the way OSGi works.  Every package in a version of Bouncy Castle should make it mandatory to use the same version otherwise it will be subject to vulnerabilities in other versions.  Currently by not specifying the version of every package it is allowing OSGi wiring models to determine which Bouncy Castle version is being chosen.

In my case PROV was version 1.38 and other parts were LTS version 2.73.4.

One other source of vulnerability is the packages must be signed or someone could alter the Manifest file to change the versions that get loaded.

**Comment by penhorwood** [comment]
Your new version works without any alteration.  We are getting close to make this work for all cases.

**Comment by penhorwood** [comment]
I am not sure how Bouncy Castle handling its projects but the other Java versions appears to have the same issues you fixed here.  You might want to communicate this OSGi stuff to them.

**Comment by dghgit** [comment]
Yes, now that it's "working properly" I'll get these updates propagated.

**Comment by penhorwood** [comment]
Thanks!!!

**Comment by dghgit** [comment]
I've just uploaded 2.73.4 which should fix this issue - it's not up on Maven yet so there's still room to tweak it. It's available at https://www.bouncycastle.org/lts-java/ If someone would confirm the OSGI configurations actually work it would be appreciated.

**Comment by penhorwood** [comment]
2.73.4 works for me.  Thanks for all the work you put into this.  Much appreciated.

**Comment by dghgit** [comment]
Thanks. I'll get it up on Maven and officially announce. Now closing as done. Anything further comes up please let us know.
