### ISSUE TITLE
Wrong information in Provider.id info 

### ISSUE THREAD

**Issue by penhorwood** [bcgit/bc-lts-java#2]
It appears that the package is reporting itself as a snapshot.

![image](https://github.com/bcgit/bc-lts-java/assets/1919238/68f444a0-5a89-4fbe-95a6-4ba08e6d07b6)

**Comment by dghgit** [comment]
This is from the jar on Maven Central.

java -cp test/build/libs/test-2.73.5-SNAPSHOT.jar:bcprov-lts8on-2.73.4.jar org.bouncycastle.test.DumpAliases | grep Provider
Provider.id className => org.bouncycastle.jce.provider.BouncyCastleProvider
Provider.id version => 2.7304
Provider.id name => BC
Provider.id info => BouncyCastle Security Provider (LTS edition) v2.73.4

Dump alias obviously won't exist in your case, but all it's doing is dumping the aliases out of the provider table. I think you might actually have a SNAPSHOT release.
